version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db

  ui:
    env_file: .env
    build: ./ui
    image: dev05/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - frontend

  post:
    env_file: .env
    build: ./post-py
    image: dev05/post:${POST_VERSION}
    networks:
      - backend
      - frontend

  comment:
    env_file: .env
    build: ./comment
    image: dev05/comment:${COMMENT_VERSION}
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  backend:
  frontend: